### ISSUE TITLE
what is the license here for netty-jssc?

### ISSUE THREAD

**Issue by tttomat19** [jkschneider/netty-jssc#1]
Hi @jkschneider, what is the license for that project? Could you please add one? (Or maybe permit me to use it under some license).
By default github terms does not allow me to do anything except fork, basically.
Thank you.

**Comment by jkschneider** [comment]
Added an Apache license. Hopefully that is permissive enough, as I have no qualms with its use for any purpose.

I haven't had a need for this connector for some years, so you'll probably want to upgrade the underlying netty libraries.

**Comment by tttomat19** [comment]
Thanks a lot
